/********************************************************************
* mainDic.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error mainDic.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevmainDic();
extern G__DLLEXPORT void G__set_cpp_environmentmainDic();
extern G__DLLEXPORT void G__cpp_setup_tagtablemainDic();
extern G__DLLEXPORT void G__cpp_setup_inheritancemainDic();
extern G__DLLEXPORT void G__cpp_setup_typetablemainDic();
extern G__DLLEXPORT void G__cpp_setup_memvarmainDic();
extern G__DLLEXPORT void G__cpp_setup_globalmainDic();
extern G__DLLEXPORT void G__cpp_setup_memfuncmainDic();
extern G__DLLEXPORT void G__cpp_setup_funcmainDic();
extern G__DLLEXPORT void G__cpp_setupmainDic();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EventMainCh.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__mainDicLN_TClass;
extern G__linked_taginfo G__mainDicLN_TBuffer;
extern G__linked_taginfo G__mainDicLN_TMemberInspector;
extern G__linked_taginfo G__mainDicLN_TObject;
extern G__linked_taginfo G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mainDicLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mainDicLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__mainDicLN_EventMainCh;

/* STUB derived class for protected member access */
