//
// File generated by rootcint at Thu May 30 13:59:15 2019

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME mainDic
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "mainDic.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void B_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_B(void *p = 0);
   static void *newArray_B(Long_t size, void *p);
   static void delete_B(void *p);
   static void deleteArray_B(void *p);
   static void destruct_B(void *p);
   static void streamer_B(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::B*)
   {
      ::B *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::B >(0);
      static ::ROOT::TGenericClassInfo 
         instance("B", ::B::Class_Version(), "./B.h", 12,
                  typeid(::B), ::ROOT::DefineBehavior(ptr, ptr),
                  &::B::Dictionary, isa_proxy, 0,
                  sizeof(::B) );
      instance.SetNew(&new_B);
      instance.SetNewArray(&newArray_B);
      instance.SetDelete(&delete_B);
      instance.SetDeleteArray(&deleteArray_B);
      instance.SetDestructor(&destruct_B);
      instance.SetStreamerFunc(&streamer_B);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::B*)
   {
      return GenerateInitInstanceLocal((::B*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::B*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

namespace ROOTDict {
   void A_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_A(void *p = 0);
   static void *newArray_A(Long_t size, void *p);
   static void delete_A(void *p);
   static void deleteArray_A(void *p);
   static void destruct_A(void *p);
   static void streamer_A(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::A*)
   {
      ::A *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::A >(0);
      static ::ROOT::TGenericClassInfo 
         instance("A", ::A::Class_Version(), "./A.h", 15,
                  typeid(::A), ::ROOT::DefineBehavior(ptr, ptr),
                  &::A::Dictionary, isa_proxy, 0,
                  sizeof(::A) );
      instance.SetNew(&new_A);
      instance.SetNewArray(&newArray_A);
      instance.SetDelete(&delete_A);
      instance.SetDeleteArray(&deleteArray_A);
      instance.SetDestructor(&destruct_A);
      instance.SetStreamerFunc(&streamer_A);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::A*)
   {
      return GenerateInitInstanceLocal((::A*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::A*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr B::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *B::Class_Name()
{
   return "B";
}

//______________________________________________________________________________
const char *B::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::B*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int B::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::B*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void B::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::B*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *B::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::B*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
atomic_TClass_ptr A::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *A::Class_Name()
{
   return "A";
}

//______________________________________________________________________________
const char *A::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::A*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int A::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::A*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void A::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::A*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *A::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::A*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void B::Streamer(TBuffer &R__b)
{
   // Stream an object of class B.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      {
         vector<double> &R__stl =  peak_amp;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      R__b.CheckByteCount(R__s, R__c, B::IsA());
   } else {
      R__c = R__b.WriteVersion(B::IsA(), kTRUE);
      TObject::Streamer(R__b);
      {
         vector<double> &R__stl =  peak_amp;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<double>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void B::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class B.
      typedef ::B msvc_bug_workaround;
      TClass *R__cl = msvc_bug_workaround::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "peak_amp", (void*)&peak_amp);
      R__insp.InspectMember("vector<double>", (void*)&peak_amp, "peak_amp.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_B(void *p) {
      return  p ? new(p) ::B : new ::B;
   }
   static void *newArray_B(Long_t nElements, void *p) {
      return p ? new(p) ::B[nElements] : new ::B[nElements];
   }
   // Wrapper around operator delete
   static void delete_B(void *p) {
      delete ((::B*)p);
   }
   static void deleteArray_B(void *p) {
      delete [] ((::B*)p);
   }
   static void destruct_B(void *p) {
      typedef ::B current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_B(TBuffer &buf, void *obj) {
      ((::B*)obj)->::B::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::B

//______________________________________________________________________________
void A::Streamer(TBuffer &R__b)
{
   // Stream an object of class A.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      {
         vector<B*> &R__stl =  peaks;
         R__stl.clear();
         TClass *R__tcl1 = TBuffer::GetClass(typeid(B));
         if (R__tcl1==0) {
            Error("peaks streamer","Missing the TClass object for B!");
            return;
         }
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            B* R__t;
            R__t = (B*)R__b.ReadObjectAny(R__tcl1);
            R__stl.push_back(R__t);
         }
      }
      {
         vector<double> &R__stl =  id;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      R__b.CheckByteCount(R__s, R__c, A::IsA());
   } else {
      R__c = R__b.WriteVersion(A::IsA(), kTRUE);
      TObject::Streamer(R__b);
      {
         vector<B*> &R__stl =  peaks;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<B*>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<double> &R__stl =  id;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<double>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void A::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class A.
      typedef ::A msvc_bug_workaround;
      TClass *R__cl = msvc_bug_workaround::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "peaks", (void*)&peaks);
      R__insp.InspectMember("vector<B*>", (void*)&peaks, "peaks.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "id", (void*)&id);
      R__insp.InspectMember("vector<double>", (void*)&id, "id.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_A(void *p) {
      return  p ? new(p) ::A : new ::A;
   }
   static void *newArray_A(Long_t nElements, void *p) {
      return p ? new(p) ::A[nElements] : new ::A[nElements];
   }
   // Wrapper around operator delete
   static void delete_A(void *p) {
      delete ((::A*)p);
   }
   static void deleteArray_A(void *p) {
      delete [] ((::A*)p);
   }
   static void destruct_A(void *p) {
      typedef ::A current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_A(TBuffer &buf, void *obj) {
      ((::A*)obj)->::A::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::A

namespace ROOTDict {
   void vectorlEBmUgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEBmUgR_Dictionary();
   static void *new_vectorlEBmUgR(void *p = 0);
   static void *newArray_vectorlEBmUgR(Long_t size, void *p);
   static void delete_vectorlEBmUgR(void *p);
   static void deleteArray_vectorlEBmUgR(void *p);
   static void destruct_vectorlEBmUgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<B*>*)
   {
      vector<B*> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<B*>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<B*>", -2, "prec_stl/vector", 49,
                  typeid(vector<B*>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEBmUgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<B*>) );
      instance.SetNew(&new_vectorlEBmUgR);
      instance.SetNewArray(&newArray_vectorlEBmUgR);
      instance.SetDelete(&delete_vectorlEBmUgR);
      instance.SetDeleteArray(&deleteArray_vectorlEBmUgR);
      instance.SetDestructor(&destruct_vectorlEBmUgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<B*> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<B*>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEBmUgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<B*>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEBmUgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<B*> : new vector<B*>;
   }
   static void *newArray_vectorlEBmUgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<B*>[nElements] : new vector<B*>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEBmUgR(void *p) {
      delete ((vector<B*>*)p);
   }
   static void deleteArray_vectorlEBmUgR(void *p) {
      delete [] ((vector<B*>*)p);
   }
   static void destruct_vectorlEBmUgR(void *p) {
      typedef vector<B*> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<B*>

namespace ROOTDict {
   void vectorlEdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEdoublegR_Dictionary();
   static void *new_vectorlEdoublegR(void *p = 0);
   static void *newArray_vectorlEdoublegR(Long_t size, void *p);
   static void delete_vectorlEdoublegR(void *p);
   static void deleteArray_vectorlEdoublegR(void *p);
   static void destruct_vectorlEdoublegR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<double>*)
   {
      vector<double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<double>", -2, "vector.dll", 0,
                  typeid(vector<double>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(vector<double>) );
      instance.SetNew(&new_vectorlEdoublegR);
      instance.SetNewArray(&newArray_vectorlEdoublegR);
      instance.SetDelete(&delete_vectorlEdoublegR);
      instance.SetDeleteArray(&deleteArray_vectorlEdoublegR);
      instance.SetDestructor(&destruct_vectorlEdoublegR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEdoublegR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<double>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double> : new vector<double>;
   }
   static void *newArray_vectorlEdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double>[nElements] : new vector<double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEdoublegR(void *p) {
      delete ((vector<double>*)p);
   }
   static void deleteArray_vectorlEdoublegR(void *p) {
      delete [] ((vector<double>*)p);
   }
   static void destruct_vectorlEdoublegR(void *p) {
      typedef vector<double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<double>

/********************************************************
* mainDic.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtablemainDic();

extern "C" void G__set_cpp_environmentmainDic() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("B.h");
  G__add_compiledheader("A.h");
  G__cpp_reset_tagtablemainDic();
}
#include <new>
extern "C" int G__cpp_dllrevmainDic() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* B */
static int G__mainDic_249_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   B* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new B[n];
     } else {
       p = new((void*) gvp) B[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new B;
     } else {
       p = new((void*) gvp) B;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mainDicLN_B));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_249_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   B* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new B(*(B*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) B(*(B*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mainDicLN_B));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_249_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const B& obj = ((B*) G__getstructoffset())->operator=(*(B*) libp->para[0].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_249_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const B*) G__getstructoffset())->operator==(*(B*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_249_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) B::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_249_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) B::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_249_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) B::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_249_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      B::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_249_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((B*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_249_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) B::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_249_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) B::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_249_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) B::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_249_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) B::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef B G__TB;
static int G__mainDic_249_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (B*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((B*) (soff+(sizeof(B)*i)))->~G__TB();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (B*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((B*) (soff))->~G__TB();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* A */
static int G__mainDic_250_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   A* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new A[n];
     } else {
       p = new((void*) gvp) A[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new A;
     } else {
       p = new((void*) gvp) A;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mainDicLN_A));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_250_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((A*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_250_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) A::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_250_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) A::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_250_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) A::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_250_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      A::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_250_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((A*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_250_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) A::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_250_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) A::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_250_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) A::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_250_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) A::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__mainDic_250_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   A* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new A(*(A*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mainDicLN_A));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef A G__TA;
static int G__mainDic_250_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (A*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((A*) (soff+(sizeof(A)*i)))->~G__TA();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (A*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((A*) (soff))->~G__TA();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__mainDic_250_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   A* dest = (A*) G__getstructoffset();
   *dest = *(A*) libp->para[0].ref;
   const A& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* B */

/* A */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncmainDic {
 public:
  G__Sizep2memfuncmainDic(): p(&G__Sizep2memfuncmainDic::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncmainDic::*p)();
};

size_t G__get_sizep2memfuncmainDic()
{
  G__Sizep2memfuncmainDic a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancemainDic() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__mainDicLN_B))) {
     B *G__Lderived;
     G__Lderived=(B*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__mainDicLN_B),G__get_linked_tagnum(&G__mainDicLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__mainDicLN_A))) {
     A *G__Lderived;
     G__Lderived=(A*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__mainDicLN_A),G__get_linked_tagnum(&G__mainDicLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablemainDic() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::reference>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::iterator_category,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::value_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::difference_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::pointer,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::reference>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*,long>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*,long,TVirtualArray**>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::iterator_category,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::value_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::difference_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::pointer,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<B*>",117,G__get_linked_tagnum(&G__mainDicLN_vectorlEBmUcOallocatorlEBmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<B*>",117,G__get_linked_tagnum(&G__mainDicLN_vectorlEBmUcOallocatorlEBmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mainDicLN_reverse_iteratorlEvectorlEBmUcOallocatorlEBmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mainDicLN_vectorlEBmUcOallocatorlEBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<B*,allocator<B*> >::iterator>::iterator_category,iterator_traits<vector<B*,allocator<B*> >::iterator>::value_type,iterator_traits<vector<B*,allocator<B*> >::iterator>::difference_type,iterator_traits<vector<B*,allocator<B*> >::iterator>::pointer,iterator_traits<vector<B*,allocator<B*> >::iterator>::reference>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlErandom_access_iterator_tagcOBmUcOlongcOBmUmUcOBmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,B*>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlErandom_access_iterator_tagcOBmUcOlongcOBmUmUcOBmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,B*,long>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlErandom_access_iterator_tagcOBmUcOlongcOBmUmUcOBmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,B*,long,B**>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlErandom_access_iterator_tagcOBmUcOlongcOBmUmUcOBmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mainDicLN_reverse_iteratorlEvectorlEBmUcOallocatorlEBmUgRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__mainDicLN_vectorlEBmUcOallocatorlEBmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<B*,allocator<B*> >::const_iterator>::iterator_category,iterator_traits<vector<B*,allocator<B*> >::const_iterator>::value_type,iterator_traits<vector<B*,allocator<B*> >::const_iterator>::difference_type,iterator_traits<vector<B*,allocator<B*> >::const_iterator>::pointer,iterator_traits<vector<B*,allocator<B*> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlErandom_access_iterator_tagcOBmUcOlongcOBmUmUcOBmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* B */
static void G__setup_memvarB(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__mainDicLN_B));
   { B *p; p=(B*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->peak_amp)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__mainDicLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"peak_amp=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mainDicLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* A */
static void G__setup_memvarA(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__mainDicLN_A));
   { A *p; p=(A*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->peaks)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__mainDicLN_vectorlEBmUcOallocatorlEBmUgRsPgR),G__defined_typename("vector<B*>"),-1,1,"peaks=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->id)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__mainDicLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"id=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mainDicLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarmainDic() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncB(void) {
   /* B */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__mainDicLN_B));
   G__memfunc_setup("B",66,G__mainDic_249_0_1, 105, G__get_linked_tagnum(&G__mainDicLN_B), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("B",66,G__mainDic_249_0_2, 105, G__get_linked_tagnum(&G__mainDicLN_B), -1, 0, 1, 1, 1, 0, "u 'B' - 11 - -", "copy constructor", (void*) NULL, 0);
   G__memfunc_setup("operator=",937,G__mainDic_249_0_3, 117, G__get_linked_tagnum(&G__mainDicLN_B), -1, 1, 1, 1, 1, 1, "u 'B' - 11 - -", "assignment", (void*) NULL, 0);
   G__memfunc_setup("operator==",998,G__mainDic_249_0_4, 105, -1, -1, 0, 1, 1, 1, 8, "u 'B' - 11 - -", "equality", (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__mainDic_249_0_5, 85, G__get_linked_tagnum(&G__mainDicLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&B::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__mainDic_249_0_6, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&B::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__mainDic_249_0_7, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&B::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__mainDic_249_0_8, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&B::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__mainDicLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__mainDic_249_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__mainDic_249_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&B::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__mainDic_249_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&B::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__mainDic_249_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&B::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__mainDic_249_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&B::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~B", 192, G__mainDic_249_0_17, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncA(void) {
   /* A */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__mainDicLN_A));
   G__memfunc_setup("A",65,G__mainDic_250_0_1, 105, G__get_linked_tagnum(&G__mainDicLN_A), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__mainDic_250_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__mainDic_250_0_3, 85, G__get_linked_tagnum(&G__mainDicLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&A::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__mainDic_250_0_4, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&A::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__mainDic_250_0_5, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&A::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__mainDic_250_0_6, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&A::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__mainDicLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__mainDic_250_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__mainDic_250_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&A::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__mainDic_250_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&A::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__mainDic_250_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&A::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__mainDic_250_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&A::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("A", 65, G__mainDic_250_0_15, (int) ('i'), G__get_linked_tagnum(&G__mainDicLN_A), -1, 0, 1, 1, 1, 0, "u 'A' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~A", 191, G__mainDic_250_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__mainDic_250_0_17, (int) ('u'), G__get_linked_tagnum(&G__mainDicLN_A), -1, 1, 1, 1, 1, 0, "u 'A' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncmainDic() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalmainDic() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcmainDic() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__mainDicLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__mainDicLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__mainDicLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__mainDicLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__mainDicLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mainDicLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR = { "iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*,ROOT::TSchemaHelper&>" , 115 , -1 };
G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mainDicLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR = { "iterator<random_access_iterator_tag,TVirtualArray*,long,TVirtualArray**,TVirtualArray*&>" , 115 , -1 };
G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__mainDicLN_B = { "B" , 99 , -1 };
G__linked_taginfo G__mainDicLN_A = { "A" , 99 , -1 };
G__linked_taginfo G__mainDicLN_vectorlEBmUcOallocatorlEBmUgRsPgR = { "vector<B*,allocator<B*> >" , 99 , -1 };
G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlEBmUcOallocatorlEBmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<B*,allocator<B*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mainDicLN_iteratorlErandom_access_iterator_tagcOBmUcOlongcOBmUmUcOBmUaNgR = { "iterator<random_access_iterator_tag,B*,long,B**,B*&>" , 115 , -1 };
G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlEBmUcOallocatorlEBmUgRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<B*,allocator<B*> >::const_iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablemainDic() {
  G__mainDicLN_TClass.tagnum = -1 ;
  G__mainDicLN_TBuffer.tagnum = -1 ;
  G__mainDicLN_TMemberInspector.tagnum = -1 ;
  G__mainDicLN_TObject.tagnum = -1 ;
  G__mainDicLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mainDicLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR.tagnum = -1 ;
  G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mainDicLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR.tagnum = -1 ;
  G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__mainDicLN_B.tagnum = -1 ;
  G__mainDicLN_A.tagnum = -1 ;
  G__mainDicLN_vectorlEBmUcOallocatorlEBmUgRsPgR.tagnum = -1 ;
  G__mainDicLN_reverse_iteratorlEvectorlEBmUcOallocatorlEBmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mainDicLN_iteratorlErandom_access_iterator_tagcOBmUcOlongcOBmUmUcOBmUaNgR.tagnum = -1 ;
  G__mainDicLN_reverse_iteratorlEvectorlEBmUcOallocatorlEBmUgRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablemainDic() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__mainDicLN_TClass);
   G__get_linked_tagnum_fwd(&G__mainDicLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__mainDicLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__mainDicLN_TObject);
   G__get_linked_tagnum_fwd(&G__mainDicLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__mainDicLN_B),sizeof(B),-1,32512,(char*)NULL,G__setup_memvarB,G__setup_memfuncB);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__mainDicLN_A),sizeof(A),-1,29952,(char*)NULL,G__setup_memvarA,G__setup_memfuncA);
   G__get_linked_tagnum_fwd(&G__mainDicLN_vectorlEBmUcOallocatorlEBmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_reverse_iteratorlEvectorlEBmUcOallocatorlEBmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_iteratorlErandom_access_iterator_tagcOBmUcOlongcOBmUmUcOBmUaNgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_reverse_iteratorlEvectorlEBmUcOallocatorlEBmUgRsPgRcLcLconst_iteratorgR);
}
extern "C" void G__cpp_setupmainDic(void) {
  G__check_setup_version(30051515,"G__cpp_setupmainDic()");
  G__set_cpp_environmentmainDic();
  G__cpp_setup_tagtablemainDic();

  G__cpp_setup_inheritancemainDic();

  G__cpp_setup_typetablemainDic();

  G__cpp_setup_memvarmainDic();

  G__cpp_setup_memfuncmainDic();
  G__cpp_setup_globalmainDic();
  G__cpp_setup_funcmainDic();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncmainDic();
  return;
}
class G__cpp_setup_initmainDic {
  public:
    G__cpp_setup_initmainDic() { G__add_setup_func("mainDic",(G__incsetup)(&G__cpp_setupmainDic)); G__call_setup_funcs(); }
   ~G__cpp_setup_initmainDic() { G__remove_setup_func("mainDic"); }
};
G__cpp_setup_initmainDic G__cpp_setup_initializermainDic;

